### PR TITLE
Fix/broken mysql dependency/#35

### PR DESCRIPTION
**Pull request by Lirt**
Connected with issue #36

### CODE REVIEW

**Comment by Martin819** [comment]
This seems legitimate to me. **+1**

**Review by inthuriel — APPROVED** [review]

**Review by epcim — APPROVED** [review]
lg

**Review by inthuriel — COMMENTED** [review]
Looks good for me

**Comment by epcim** [comment]
FYI - we will temporarily revert and will provide a fix next week: https://github.com/salt-formulas/salt-formula-galera/issues/39

**Pull request merged**
